[project]
name = "local-reference-renamer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "libcst>=1.8.2",
    "rope>=1.14.0",
]
